# Generated by Django 4.1.1 on 2022-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_phone_number_usertier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/profile_images/'),
        ),
    ]
